apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-frontend
  namespace: rag-system
  labels:
    app: rag-frontend
    project: rag-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
        - name: frontend
          image: mayank2101/rag-mlops-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: REACT_APP_API_URL
              value: "http://rag-api-service:8000"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
